[package]
name = "toy_payment_engine"
version = "0.1.0"
edition = "2021"
authors = ["Igal Alkon"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
csv = "1.1"
